# Generated by Django 3.0.3 on 2020-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_faq_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='popular',
            field=models.CharField(default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
